### PR TITLE
Add dockerfile virtual build system

### PR DESCRIPTION
**Pull request by freelinli**
Add dockerfile virtual build system

### CODE REVIEW

**Comment by unicornx** [comment]
Thanks, I will have a try when I get time on this.

**Comment by freelinli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好,这里是李晋南（向阳）。来信已收到。看后会尽快给你回复，谢谢

**Comment by unicornx** [comment]
After thinking it over, I would hope not involve docker for env setup, in purpose to:
- Setting env in Ubuntu is simple enough
- Keep the code for this course simple.

Thank you anyway and looking for more good contribution from you.

**Comment by freelinli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好,这里是李晋南（向阳）。来信已收到。看后会尽快给你回复，谢谢

**Pull request closed without merging**
